name: npmrc-test

on:
  pull_request:
  workflow_dispatch: # Allows manual invocation

jobs:
  npmrc-test:
    runs-on: ubuntu-latest
    environment: production # require manual approval for production deployments
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Install and cache JS toolchain and dependencies (node_modules)
      - name: Setup JS
        uses: ./.github/actions/js-setup

      - name: Build
        run: pnpm run build-all

      - name: Typecheck
        run: pnpm run typecheck-all

      - name: Prettier
        run: pnpm run prettier-all:check

      - name: Confirm environment variables
        run: |
          if [ -n "${{ secrets.NPM_TOKEN }}" ]; then
            echo "NPM_TOKEN is set"
          else
            echo "NPM_TOKEN is not set"
            exit 1
          fi
          if [ -n "${{ secrets.GITHUB_TOKEN }}" ]; then
            echo "GITHUB_TOKEN is set"
          else
            echo "GITHUB_TOKEN is not set"
            exit 1
          fi
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up NPM .npmrc config for NPM registry
        run: |
          # mask the token in logs
          echo "::add-mask::$NPM_TOKEN"

          if [ -f .npmrc.ci ]; then
            echo "Rendering .npmrc from .npmrc.ci template"
            # use envsubst to replace the token in the .npmrc.ci template
            envsubst '${NPM_TOKEN}' < .npmrc.ci > .npmrc
          else
            echo "No .npmrc.ci found, creating new .npmrc"
            # use envsubst to replace the token in the .npmrc template
            envsubst '${NPM_TOKEN}' <<< '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
          fi
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Debug npm config
        run: |
          if [ -s .npmrc ]; then
            echo ".npmrc exists and is not empty"
          else
            echo ".npmrc not found or empty"
          fi
